sonar.projectKey=luc-dt_spotify-pipeline
sonar.organization=luc-dt

# Exclude raw cache and build artifacts
sonar.exclusions=data/**,airflow/logs/**,.venv/**,scratch/**

# Ignore package-locking and only-binary rules that conflict with data engineering PySpark wheels
sonar.issue.ignore.multicriteria=r1,r2,r3,r4
sonar.issue.ignore.multicriteria.r1.ruleKey=docker:S8541
sonar.issue.ignore.multicriteria.r1.resourceKey=**
sonar.issue.ignore.multicriteria.r2.ruleKey=docker:S8544
sonar.issue.ignore.multicriteria.r2.resourceKey=**
sonar.issue.ignore.multicriteria.r3.ruleKey=githubactions:S8541
sonar.issue.ignore.multicriteria.r3.resourceKey=**
sonar.issue.ignore.multicriteria.r4.ruleKey=githubactions:S8544
sonar.issue.ignore.multicriteria.r4.resourceKey=**
